### ISSUE TITLE
API "/api/v0/modules/list" always fetch from internet, not from local db.

### ISSUE THREAD

**Issue by henrywang** [weldr/lorax#609] opened 2019-02-18 09:20 UTC
Environment:
Fedora 29, lorax-composer-29.26-1.fc29.x86_64
Issue:
Calling `/api/v0/modules/list` api always fetches from internet. That'll cause the UI `Loading` for a while every time entering into edit blueprint page.
**No this kind of issue on lorax-composer-29.16-1.fc29.x86_64.**
Here's a comparison between 29.26 and 29.16.

```shell
[root@m1 ~]# time curl --unix-socket /run/weldr/api.socket http://localhost:4000/api/v0/modules/list
{"limit":20,"modules":[{"group_type":"rpm","name":"0ad"},{"group_type":"rpm","name":"0ad-data"},{"group_type":"rpm","name":"0install"},{"group_type":"rpm","name":"0xFFFF"},{"group_type":"rpm","name":"2048-cli"},{"group_type":"rpm","name":"2048-cli-nocurses"},{"group_type":"rpm","name":"2048-cli-sdl"},{"group_type":"rpm","name":"2ping"},{"group_type":"rpm","name":"389-admin"},{"group_type":"rpm","name":"389-admin-console"},{"group_type":"rpm","name":"389-admin-console-doc"},{"group_type":"rpm","name":"389-adminutil"},{"group_type":"rpm","name":"389-adminutil-devel"},{"group_type":"rpm","name":"389-console"},{"group_type":"rpm","name":"389-ds"},{"group_type":"rpm","name":"389-ds-base"},{"group_type":"rpm","name":"389-ds-base-devel"},{"group_type":"rpm","name":"389-ds-base-legacy-tools"},{"group_type":"rpm","name":"389-ds-base-libs"},{"group_type":"rpm","name":"389-ds-base-snmp"}],"offset":0,"total":50474}

real    0m45.271s
user    0m0.003s
sys     0m0.006s
[root@m1 ~]# rpm -qa |grep lorax-composer
lorax-composer-29.26-1.fc29.x86_64

###########################################
[root@m1 ~]# time curl --unix-socket /run/weldr/api.socket http://localhost:4000/api/v0/modules/list
{"limit":20,"modules":[{"group_type":"rpm","name":"0ad"},{"group_type":"rpm","name":"0ad"},{"group_type":"rpm","name":"0ad-data"},{"group_type":"rpm","name":"0ad-data"},{"group_type":"rpm","name":"0install"},{"group_type":"rpm","name":"0xFFFF"},{"group_type":"rpm","name":"2048-cli"},{"group_type":"rpm","name":"2048-cli-nocurses"},{"group_type":"rpm","name":"2048-cli-sdl"},{"group_type":"rpm","name":"2ping"},{"group_type":"rpm","name":"389-admin"},{"group_type":"rpm","name":"389-admin-console"},{"group_type":"rpm","name":"389-admin-console-doc"},{"group_type":"rpm","name":"389-adminutil"},{"group_type":"rpm","name":"389-adminutil-devel"},{"group_type":"rpm","name":"389-console"},{"group_type":"rpm","name":"389-console"},{"group_type":"rpm","name":"389-ds"},{"group_type":"rpm","name":"389-ds-base"},{"group_type":"rpm","name":"389-ds-base"}],"offset":0,"total":75610}

real    0m1.181s
user    0m0.007s
sys     0m0.004s
[root@m1 ~]# rpm -qa|grep lorax-composer
lorax-composer-29.16-1.fc29.x86_64
```

**Comment by larskarlitski** [comment] 2019-02-18 09:26
> Calling `/api/v0/modules/list` api always fetches from internet.

I can reproduce that it's slow, but it doesn't fetch anything additional from the internet for me. I think the problem is a computational complexity issue in `_unique_dicts`. Could you please test if https://github.com/weldr/lorax/pull/610 fixes this issue for you?

Thanks for filing this bug!

**Comment by bcl** [comment] 2019-02-18 16:55
To monitor whether or not it is re-fetching metadata from the repos you could monitor the lorax-composer process with lsof -p <pid> and see if there are any tcp lines connecting to the configured repos.

**Comment by larskarlitski** [comment] 2019-03-15 10:03
This should be fixed with https://github.com/weldr/lorax/pull/620

**Closed** 2019-03-15 15:28 UTC
